# Generated by Django 5.0.6 on 2024-05-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clubs',
            new_name='Club',
        ),
    ]
