# Generated by Django 5.0.6 on 2024-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0003_rename_books_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgot',
            fields=[
                ('Student_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_activate', models.BooleanField(default=False)),
                ('is_added_address', models.BooleanField(default=False)),
                ('otp', models.CharField(default='11111', max_length=10)),
            ],
        ),
    ]
