# Generated by Django 5.0.6 on 2024-06-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0004_forgot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forgot',
        ),
    ]
